services:
  beacond:
    image: ghcr.io/rollkit/beacon-kit:v0.1.3
    container_name: beacond
    volumes:
      - ./testing/files:/beacon-kit/testing/files
      - ./.tmp:/beacon-kit/.tmp
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /beacon-kit/testing/files/entrypoint.sh
    depends_on:
      celestia-network-validator:
        condition: service_healthy
      celestia-network-bridge:
        condition: service_healthy
      reth:
        condition: service_started
    networks:
      - rollkit-network

  reth:
    image: ghcr.io/paradigmxyz/reth # Use the official Reth image
    container_name: reth
    ports:
      - "30303:30303" # P2P port
      - "8545:8545" # HTTP port
      - "8551:8551" # Auth RPC port
    volumes:
      - ./testing/files:/testapp_files # Mount the directory for test app files
      - ./.tmp:/.tmp # Mount a temporary directory for data
    command: |
      node
      --chain /testapp_files/eth-genesis.json
      --http
      --http.addr 0.0.0.0
      --http.api eth,net,debug
      --authrpc.addr 0.0.0.0
      --authrpc.jwtsecret /testapp_files/jwt.hex
      --datadir /.tmp/eth-home
      --ipcpath /.tmp/eth-home/eth-engine.ipc
    networks:
      - rollkit-network

  celestia-network-validator:
    image: ghcr.io/celestiaorg/celestia-app:v3.3.1-mocha
    container_name: celestia-network-validator
    volumes:
      - ./.tmp/celestia-validator:/home/celestia
      - ./testing/files/celestia-validator:/testapp_files
    ports:
      - "9090:9090"
      - "26656:26656"
      - "26657:26657"
    entrypoint: /testapp_files/entrypoint.sh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/bin/sh -c ''BLOCK_HEIGHT=$(curl -sf http://localhost:26657/status | jq -r .result.sync_info.latest_block_height); if [ "$$BLOCK_HEIGHT" -gt 1 ]; then exit 0; else echo "Block height too low: $$BLOCK_HEIGHT"; exit 1; fi''',
        ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - rollkit-network

  celestia-network-bridge:
    image: ghcr.io/celestiaorg/celestia-node:v0.20.1-mocha
    container_name: celestia-network-bridge
    environment:
      - P2P_NETWORK=private
      - "CELESTIA_CUSTOM=private:BFCEC14C1A50F3549777ED9EF350A9D79BE826C7836CD4FBEFE9C9C4F61A111F"
    volumes:
      - ./testing/files/celestia-bridge:/testapp_files
      - ./.tmp/celestia-bridge:/home/celestia
    entrypoint: /testapp_files/entrypoint.sh
    command: celestia bridge start --p2p.network private --core.ip celestia-network-validator --rpc.addr 0.0.0.0 --rpc.port 26658 --keyring.keyname bridge
    ports:
      - "26658:26658"
      - "2121:2121"
    depends_on:
      celestia-network-validator:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'AUTH_TOKEN=$(celestia bridge auth read --node.store=/home/celestia 2>/dev/null | tail -n 1); OUTPUT=$(curl -sf --max-time 0.5 -X POST -H "Content-type: application/json" -H "Accept: application/json" -H "Authorization: Bearer $$AUTH_TOKEN" -d ''{"id":1,"jsonrpc":"2.0","method":"header.SyncWait","params":[]}'' http://0.0.0.0:26658); if [ $$? -eq 0 ]; then exit 0; else echo "Catching up. $$OUTPUT"; exit 1; fi ',
        ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - rollkit-network

  simapp-validator:
    image: ghcr.io/celestiaorg/celestia-zkevm-ibc-demo/simapp:latest
    container_name: simapp-validator
    volumes:
      - ./.tmp/simapp-validator:/home/celestia
      - ./testing/files/simapp-validator:/testapp_files
    entrypoint: /testapp_files/entrypoint.sh
    ports:
      - "9190:9090"
      - "5123:26657"
    networks:
      - rollkit-network

  celestia-prover:
    image: ghcr.io/celestiaorg/celestia-zkevm-ibc-demo/celestia-prover:latest
    container_name: celestia-prover
    environment:
      # TENDERMINT_RPC_URL should be the SimApp which is acting as a substitute
      # for Celestia (with IBC Eurekea enabled).
      - TENDERMINT_RPC_URL=http://simapp-validator:26657
      - RPC_URL=http://reth:8545
      - CELESTIA_PROTO_DESCRIPTOR_PATH=proto_descriptor.bin
    ports:
      - "50051:50051"
    depends_on:
      beacond:
        condition: service_started
    networks:
      - rollkit-network

  evm-prover:
    image: ghcr.io/celestiaorg/celestia-zkevm-ibc-demo/evm-prover:latest
    container_name: evm-prover
    environment:
      # TENDERMINT_RPC_URL should be the SimApp which is acting as a substitute
      # for Celestia (with IBC Eurekea enabled).
      - TENDERMINT_RPC_URL=http://simapp-validator:26657
      - RPC_URL=http://reth:8545
      - EVM_PROTO_DESCRIPTOR_PATH=proto_descriptor.bin
    ports:
      - "50052:50052"
    depends_on:
      beacond:
        condition: service_started
    networks:
      - rollkit-network

networks:
  rollkit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
