name: setup
description: "Setup environment for Rust projects"

runs:
  using: composite
  steps:
    - name: "Check out the repo"
      uses: "actions/checkout@v4"
    - name: Update Rust
      shell: bash
      run: rustup update
    - name: Set default Rust toolchain to stable
      shell: bash
      run: rustup default stable
    - name: Setup Protoc
      uses: taiki-e/install-action@protoc
