// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: prover/v1/prover.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProverService_Info_FullMethodName                     = "/celestia.prover.v1.ProverService/Info"
	ProverService_ProveStateTransition_FullMethodName     = "/celestia.prover.v1.ProverService/ProveStateTransition"
	ProverService_ProveStateMembership_FullMethodName     = "/celestia.prover.v1.ProverService/ProveStateMembership"
	ProverService_InfoFast_FullMethodName                 = "/celestia.prover.v1.ProverService/InfoFast"
	ProverService_ProveStateTransitionFast_FullMethodName = "/celestia.prover.v1.ProverService/ProveStateTransitionFast"
	ProverService_ProveStateMembershipFast_FullMethodName = "/celestia.prover.v1.ProverService/ProveStateMembershipFast"
)

// ProverServiceClient is the client API for ProverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProverServiceClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	ProveStateTransition(ctx context.Context, in *ProveStateTransitionRequest, opts ...grpc.CallOption) (*ProveStateTransitionResponse, error)
	ProveStateMembership(ctx context.Context, in *ProveStateMembershipRequest, opts ...grpc.CallOption) (*ProveStateMembershipResponse, error)
	InfoFast(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	ProveStateTransitionFast(ctx context.Context, in *ProveStateTransitionRequest, opts ...grpc.CallOption) (*ProveStateTransitionResponse, error)
	ProveStateMembershipFast(ctx context.Context, in *ProveStateMembershipRequest, opts ...grpc.CallOption) (*ProveStateMembershipResponse, error)
}

type proverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProverServiceClient(cc grpc.ClientConnInterface) ProverServiceClient {
	return &proverServiceClient{cc}
}

func (c *proverServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, ProverService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proverServiceClient) ProveStateTransition(ctx context.Context, in *ProveStateTransitionRequest, opts ...grpc.CallOption) (*ProveStateTransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveStateTransitionResponse)
	err := c.cc.Invoke(ctx, ProverService_ProveStateTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proverServiceClient) ProveStateMembership(ctx context.Context, in *ProveStateMembershipRequest, opts ...grpc.CallOption) (*ProveStateMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveStateMembershipResponse)
	err := c.cc.Invoke(ctx, ProverService_ProveStateMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proverServiceClient) InfoFast(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, ProverService_InfoFast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proverServiceClient) ProveStateTransitionFast(ctx context.Context, in *ProveStateTransitionRequest, opts ...grpc.CallOption) (*ProveStateTransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveStateTransitionResponse)
	err := c.cc.Invoke(ctx, ProverService_ProveStateTransitionFast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proverServiceClient) ProveStateMembershipFast(ctx context.Context, in *ProveStateMembershipRequest, opts ...grpc.CallOption) (*ProveStateMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveStateMembershipResponse)
	err := c.cc.Invoke(ctx, ProverService_ProveStateMembershipFast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProverServiceServer is the server API for ProverService service.
// All implementations must embed UnimplementedProverServiceServer
// for forward compatibility.
type ProverServiceServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	ProveStateTransition(context.Context, *ProveStateTransitionRequest) (*ProveStateTransitionResponse, error)
	ProveStateMembership(context.Context, *ProveStateMembershipRequest) (*ProveStateMembershipResponse, error)
	InfoFast(context.Context, *InfoRequest) (*InfoResponse, error)
	ProveStateTransitionFast(context.Context, *ProveStateTransitionRequest) (*ProveStateTransitionResponse, error)
	ProveStateMembershipFast(context.Context, *ProveStateMembershipRequest) (*ProveStateMembershipResponse, error)
	mustEmbedUnimplementedProverServiceServer()
}

// UnimplementedProverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProverServiceServer struct{}

func (UnimplementedProverServiceServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedProverServiceServer) ProveStateTransition(context.Context, *ProveStateTransitionRequest) (*ProveStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveStateTransition not implemented")
}
func (UnimplementedProverServiceServer) ProveStateMembership(context.Context, *ProveStateMembershipRequest) (*ProveStateMembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveStateMembership not implemented")
}
func (UnimplementedProverServiceServer) InfoFast(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InfoFast not implemented")
}
func (UnimplementedProverServiceServer) ProveStateTransitionFast(context.Context, *ProveStateTransitionRequest) (*ProveStateTransitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveStateTransitionFast not implemented")
}
func (UnimplementedProverServiceServer) ProveStateMembershipFast(context.Context, *ProveStateMembershipRequest) (*ProveStateMembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveStateMembershipFast not implemented")
}
func (UnimplementedProverServiceServer) mustEmbedUnimplementedProverServiceServer() {}
func (UnimplementedProverServiceServer) testEmbeddedByValue()                       {}

// UnsafeProverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProverServiceServer will
// result in compilation errors.
type UnsafeProverServiceServer interface {
	mustEmbedUnimplementedProverServiceServer()
}

func RegisterProverServiceServer(s grpc.ServiceRegistrar, srv ProverServiceServer) {
	// If the following call pancis, it indicates UnimplementedProverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProverService_ServiceDesc, srv)
}

func _ProverService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProverService_ProveStateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverServiceServer).ProveStateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverService_ProveStateTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverServiceServer).ProveStateTransition(ctx, req.(*ProveStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProverService_ProveStateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveStateMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverServiceServer).ProveStateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverService_ProveStateMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverServiceServer).ProveStateMembership(ctx, req.(*ProveStateMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProverService_InfoFast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverServiceServer).InfoFast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverService_InfoFast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverServiceServer).InfoFast(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProverService_ProveStateTransitionFast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveStateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverServiceServer).ProveStateTransitionFast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverService_ProveStateTransitionFast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverServiceServer).ProveStateTransitionFast(ctx, req.(*ProveStateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProverService_ProveStateMembershipFast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveStateMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverServiceServer).ProveStateMembershipFast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverService_ProveStateMembershipFast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverServiceServer).ProveStateMembershipFast(ctx, req.(*ProveStateMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProverService_ServiceDesc is the grpc.ServiceDesc for ProverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "celestia.prover.v1.ProverService",
	HandlerType: (*ProverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _ProverService_Info_Handler,
		},
		{
			MethodName: "ProveStateTransition",
			Handler:    _ProverService_ProveStateTransition_Handler,
		},
		{
			MethodName: "ProveStateMembership",
			Handler:    _ProverService_ProveStateMembership_Handler,
		},
		{
			MethodName: "InfoFast",
			Handler:    _ProverService_InfoFast_Handler,
		},
		{
			MethodName: "ProveStateTransitionFast",
			Handler:    _ProverService_ProveStateTransitionFast_Handler,
		},
		{
			MethodName: "ProveStateMembershipFast",
			Handler:    _ProverService_ProveStateMembershipFast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prover/v1/prover.proto",
}
