// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: ibc/lightclients/groth16/v1/groth16.proto

package groth16

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientState defines a groth16 light client that is able to track the state of
// an EVM roll-up. ClientState contains two holds two keys that are needed to
// verify IBC packets. One key is for verifying state transition proofs. The
// other key is for verifying state membership proofs.
type ClientState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// LatestHeight is the latest block height on the EVM roll-up.
	LatestHeight uint64 `protobuf:"varint,1,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	// StateTransitionVerifierKey is the verifier key that should be used when
	// verifying Groth16 state transition proofs. These proofs verify a rollup's
	// state root after the state transition has been applied. Only the BN254
	// curve is supported.
	StateTransitionVerifierKey string `protobuf:"bytes,2,opt,name=state_transition_verifier_key,json=stateTransitionVerifierKey,proto3" json:"state_transition_verifier_key,omitempty"`
	// CodeCommitment is a commitment over the roll-up's source code.
	CodeCommitment []byte `protobuf:"bytes,3,opt,name=code_commitment,json=codeCommitment,proto3" json:"code_commitment,omitempty"`
	// GenesisStateRoot is the state root of the EVM roll-up's genesis block.
	GenesisStateRoot []byte `protobuf:"bytes,4,opt,name=genesis_state_root,json=genesisStateRoot,proto3" json:"genesis_state_root,omitempty"`
	// StateMembershipVerifierKey is the key used to verify state membership
	// (a.k.a inclusion) proofs.
	StateMembershipVerifierKey []byte `protobuf:"bytes,5,opt,name=state_membership_verifier_key,json=stateMembershipVerifierKey,proto3" json:"state_membership_verifier_key,omitempty"`
	Groth16Vk                  []byte `protobuf:"bytes,6,opt,name=groth16_vk,json=groth16Vk,proto3" json:"groth16_vk,omitempty"`
}

func (x *ClientState) Reset() {
	*x = ClientState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientState) ProtoMessage() {}

func (x *ClientState) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientState.ProtoReflect.Descriptor instead.
func (*ClientState) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_groth16_v1_groth16_proto_rawDescGZIP(), []int{0}
}

func (x *ClientState) GetLatestHeight() uint64 {
	if x != nil {
		return x.LatestHeight
	}
	return 0
}

func (x *ClientState) GetStateTransitionVerifierKey() string {
	if x != nil {
		return x.StateTransitionVerifierKey
	}
	return ""
}

func (x *ClientState) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *ClientState) GetGenesisStateRoot() []byte {
	if x != nil {
		return x.GenesisStateRoot
	}
	return nil
}

func (x *ClientState) GetStateMembershipVerifierKey() []byte {
	if x != nil {
		return x.StateMembershipVerifierKey
	}
	return nil
}

func (x *ClientState) GetGroth16Vk() []byte {
	if x != nil {
		return x.Groth16Vk
	}
	return nil
}

// ConsensusState is the trusted view of the state of a state machine at a
// particular Height. It MUST contain sufficient information to enable the
// ValidityPredicate to validate state updates, which can then be used to
// generate new ConsensusStates. It MUST be serialisable in a canonical fashion
// so that remote parties, such as remote state machines, can check whether a
// particular ConsensusState was stored by a particular state machine. It MUST
// be introspectable by the state machine whose view it represents, i.e., a
// state machine can look up its own ConsensusStates at past Heights.
type ConsensusState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// HeaderTimestamp is the timestamp of an EVM header at a particular block
	// height.
	HeaderTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=header_timestamp,json=headerTimestamp,proto3" json:"header_timestamp,omitempty"`
	// StateRoot is the state root of the EVM rollup at a particular block height.
	StateRoot []byte `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
}

func (x *ConsensusState) Reset() {
	*x = ConsensusState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusState) ProtoMessage() {}

func (x *ConsensusState) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusState.ProtoReflect.Descriptor instead.
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_groth16_v1_groth16_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusState) GetHeaderTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.HeaderTimestamp
	}
	return nil
}

func (x *ConsensusState) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

// Header defines a struct that is used to update the consensus state of the groth16 light client.
type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// StateTransitionProof is a serialized groth16 proof that the given state transition is valid.
	// If a proof with 0 bytes is provided, it is assumed to be a mock proof.
	StateTransitionProof []byte `protobuf:"bytes,1,opt,name=state_transition_proof,json=stateTransitionProof,proto3" json:"state_transition_proof,omitempty"`
	PublicValues         []byte `protobuf:"bytes,2,opt,name=public_values,json=publicValues,proto3" json:"public_values,omitempty"`
	// TrustedHeight is the last verified height of the rollup. This is used to retrieve the previous
	// state root with which the proof is verified against.
	TrustedHeight int64 `protobuf:"varint,3,opt,name=trusted_height,json=trustedHeight,proto3" json:"trusted_height,omitempty"`
	// NewestHeaderHash is the last block's hash on the EVM roll-upup.
	NewestHeaderHash []byte `protobuf:"bytes,4,opt,name=newest_header_hash,json=newestHeaderHash,proto3" json:"newest_header_hash,omitempty"`
	// OldestHeaderHash is the earliest block's hash on the EVM roll-up
	OldestHeaderHash []byte `protobuf:"bytes,5,opt,name=oldest_header_hash,json=oldestHeaderHash,proto3" json:"oldest_header_hash,omitempty"`
	// CelestiaHeaderHashes is the range of Celestia blocks that include all
	// of the blob data the EVM roll-up has posted from oldest_header_hash to
	CelestiaHeaderHashes [][]byte `protobuf:"bytes,6,rep,name=celestia_header_hashes,json=celestiaHeaderHashes,proto3" json:"celestia_header_hashes,omitempty"`
	// NewestStateRoot is the computed state root of the EVM roll-up after
	// processing blocks from oldest_header_hash to newest_header_hash
	NewestStateRoot []byte `protobuf:"bytes,7,opt,name=newest_state_root,json=newestStateRoot,proto3" json:"newest_state_root,omitempty"`
	// NewestHeight is the most recent block number of the EVM roll-up
	NewestHeight uint64 `protobuf:"varint,8,opt,name=newest_height,json=newestHeight,proto3" json:"newest_height,omitempty"`
	// Timestamp is the timestamp of an EVM header at the new height.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_ibc_lightclients_groth16_v1_groth16_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetStateTransitionProof() []byte {
	if x != nil {
		return x.StateTransitionProof
	}
	return nil
}

func (x *Header) GetPublicValues() []byte {
	if x != nil {
		return x.PublicValues
	}
	return nil
}

func (x *Header) GetTrustedHeight() int64 {
	if x != nil {
		return x.TrustedHeight
	}
	return 0
}

func (x *Header) GetNewestHeaderHash() []byte {
	if x != nil {
		return x.NewestHeaderHash
	}
	return nil
}

func (x *Header) GetOldestHeaderHash() []byte {
	if x != nil {
		return x.OldestHeaderHash
	}
	return nil
}

func (x *Header) GetCelestiaHeaderHashes() [][]byte {
	if x != nil {
		return x.CelestiaHeaderHashes
	}
	return nil
}

func (x *Header) GetNewestStateRoot() []byte {
	if x != nil {
		return x.NewestStateRoot
	}
	return nil
}

func (x *Header) GetNewestHeight() uint64 {
	if x != nil {
		return x.NewestHeight
	}
	return 0
}

func (x *Header) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_ibc_lightclients_groth16_v1_groth16_proto protoreflect.FileDescriptor

var file_ibc_lightclients_groth16_v1_groth16_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x62, 0x63, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x67, 0x72, 0x6f, 0x74, 0x68, 0x31, 0x36, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72,
	0x6f, 0x74, 0x68, 0x31, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x63, 0x65, 0x6c,
	0x65, 0x73, 0x74, 0x69, 0x61, 0x2e, 0x69, 0x62, 0x63, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x6f, 0x74, 0x68, 0x31, 0x36, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xae, 0x02, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x41, 0x0a, 0x1d, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1a,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f,
	0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0e, 0x63, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x10, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f,
	0x74, 0x12, 0x41, 0x0a, 0x1d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x1a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x74, 0x68, 0x31, 0x36, 0x5f,
	0x76, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x74, 0x68, 0x31,
	0x36, 0x56, 0x6b, 0x22, 0x76, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x45, 0x0a, 0x10, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x22, 0xa7, 0x03, 0x0a, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x16, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x65, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x65, 0x77, 0x65,
	0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x6e, 0x65, 0x77, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74,
	0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x10, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x34, 0x0a, 0x16, 0x63, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61,
	0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x14, 0x63, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x65,
	0x77, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x6e, 0x65, 0x77, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x65, 0x73, 0x74,
	0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6e,
	0x65, 0x77, 0x65, 0x73, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x62, 0x63, 0x2f, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x72, 0x6f, 0x74, 0x68, 0x31,
	0x36, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ibc_lightclients_groth16_v1_groth16_proto_rawDescOnce sync.Once
	file_ibc_lightclients_groth16_v1_groth16_proto_rawDescData = file_ibc_lightclients_groth16_v1_groth16_proto_rawDesc
)

func file_ibc_lightclients_groth16_v1_groth16_proto_rawDescGZIP() []byte {
	file_ibc_lightclients_groth16_v1_groth16_proto_rawDescOnce.Do(func() {
		file_ibc_lightclients_groth16_v1_groth16_proto_rawDescData = protoimpl.X.CompressGZIP(file_ibc_lightclients_groth16_v1_groth16_proto_rawDescData)
	})
	return file_ibc_lightclients_groth16_v1_groth16_proto_rawDescData
}

var file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ibc_lightclients_groth16_v1_groth16_proto_goTypes = []any{
	(*ClientState)(nil),           // 0: celestia.ibc.lightclients.groth16.v1.ClientState
	(*ConsensusState)(nil),        // 1: celestia.ibc.lightclients.groth16.v1.ConsensusState
	(*Header)(nil),                // 2: celestia.ibc.lightclients.groth16.v1.Header
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_ibc_lightclients_groth16_v1_groth16_proto_depIdxs = []int32{
	3, // 0: celestia.ibc.lightclients.groth16.v1.ConsensusState.header_timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: celestia.ibc.lightclients.groth16.v1.Header.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ibc_lightclients_groth16_v1_groth16_proto_init() }
func file_ibc_lightclients_groth16_v1_groth16_proto_init() {
	if File_ibc_lightclients_groth16_v1_groth16_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ClientState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConsensusState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ibc_lightclients_groth16_v1_groth16_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ibc_lightclients_groth16_v1_groth16_proto_goTypes,
		DependencyIndexes: file_ibc_lightclients_groth16_v1_groth16_proto_depIdxs,
		MessageInfos:      file_ibc_lightclients_groth16_v1_groth16_proto_msgTypes,
	}.Build()
	File_ibc_lightclients_groth16_v1_groth16_proto = out.File
	file_ibc_lightclients_groth16_v1_groth16_proto_rawDesc = nil
	file_ibc_lightclients_groth16_v1_groth16_proto_goTypes = nil
	file_ibc_lightclients_groth16_v1_groth16_proto_depIdxs = nil
}
