name: rust

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lints:
    name: fmt-and-clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: "Set up environment"
        uses: ./.github/setup

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy

  build-blevm:
    name: build-blevm
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: "Set up environment"
        uses: ./.github/setup
      - name: Build
        run: cargo build --release --locked
        working-directory: ./provers/blevm/blevm/

  build-blevm-script:
    name: build-blevm-script
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: "Set up environment"
        uses: ./.github/setup
      - name: Build
        run: cargo build --release --locked
        working-directory: ./provers/blevm/script/

  build-celestia-prover:
    name: build-celestia-prover
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: "Set up environment"
        uses: ./.github/setup
      - name: Build
        run: cargo build --bin celestia-prover --release --locked
