name: rust

on:
  push:
    branches: [main]
  pull_request:

env:
  SP1_VERSION: 4.1.2

jobs:
  lint-celestia-prover:
    name: lint-celestia-prover
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: "Set up environment"
        uses: ./.github/setup

      - name: Install SP1 toolchain
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version ${{env.SP1_VERSION}} --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version
          rustc +succinct --version

      - name: Run cargo fmt
        run: cargo fmt --check
        working-directory: .

  lint-evm-prover:
    name: lint-evm-prover
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: "Set up environment"
        uses: ./.github/setup

      - name: Install SP1 toolchain
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version ${{env.SP1_VERSION}} --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version
          rustc +succinct --version

      - name: Run cargo fmt
        run: cargo fmt --check
        working-directory: ./provers/evm-prover/

  build-evm-prover:
    name: build-evm-prover
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache SP1 programs
        id: cache-sp1-programs
        uses: actions/cache@v4
        with:
          path: |
            ./target/elf-compilation/riscv32im-succinct-zkvm-elf/release/*
          key: ${{ runner.os }}-sp1-${{ hashFiles('Cargo.lock', 'Cargo.toml', 'provers/blevm/**') }}
      - name: "Set up environment"
        uses: ./.github/setup

      - name: Install SP1 toolchain
        if: (steps.cache-sp1-programs.outputs.cache-hit != 'true')
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version ${{env.SP1_VERSION}} --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version
          rustc +succinct --version

      - name: Build
        run: cargo check --release --locked
        working-directory: ./provers/evm-prover

  build-celestia-prover:
    name: build-celestia-prover
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cache SP1 programs
        id: cache-sp1-programs
        uses: actions/cache@v4
        with:
          path: |
            ./target/elf-compilation/riscv32im-succinct-zkvm-elf/release/*
          key: ${{ runner.os }}-sp1-${{ hashFiles('solidity-ibc-eureka/Cargo.lock', 'solidity-ibc-eureka/Cargo.toml', 'solidity-ibc-eureka/programs/**', 'solidity-ibc-eureka/abi/**') }}

      - name: "Set up environment"
        uses: ./.github/setup
      - name: Install SP1 toolchain
        if: (steps.cache-sp1-programs.outputs.cache-hit != 'true')
        shell: bash
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version ${{env.SP1_VERSION}} --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version
          rustc +succinct --version

      - name: Install just
        uses: extractions/setup-just@v3
        with:
          just-version: "1.40.0"

      - name: Build SP1 programs in solidity-ibc-eureka
        if: (steps.cache-sp1-programs.outputs.cache-hit != 'true')
        run: just build-sp1-programs
        working-directory: ./solidity-ibc-eureka

      - name: Build celestia prover
        run: cargo check --release --locked
        working-directory: ./provers/celestia-prover/
