# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml
name: rust

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lints:
    name: fmt-and-clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: "Set up environment"
        uses: ./.github/setup

      - name: Install SP1 toolchain
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/succinctlabs/sp1/v3.4.0/sp1up/install | bash
          ~/.sp1/bin/sp1up --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  build-blevm:
    name: build-blevm
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: "Set up environment"
        uses: ./.github/setup
      - name: Install SP1 toolchain
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/succinctlabs/sp1/v3.4.0/sp1up/install | bash
          ~/.sp1/bin/sp1up --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin blevm --release --locked

  build-blevm-script:
    name: build-blevm-script
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: "Set up environment"
        uses: ./.github/setup
      - name: Install SP1 toolchain
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/succinctlabs/sp1/v3.4.0/sp1up/install | bash
          ~/.sp1/bin/sp1up --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin blevm-script --release --locked

  build-celestia-prover:
    name: build-celestia-prover
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: "Set up environment"
        uses: ./.github/setup
      - name: Install SP1 toolchain
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/succinctlabs/sp1/v3.4.0/sp1up/install | bash
          ~/.sp1/bin/sp1up --token ${{ secrets.GITHUB_TOKEN }}
          ~/.sp1/bin/cargo-prove prove --version
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin celestia-prover --release --locked
