[package]
name = "mock-update-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde_cbor = "0.11.2"
sp1-zkvm = "3.4.0"
ibc-client-tendermint-types = { workspace = true }
ibc-eureka-solidity-types = { workspace = true }
alloy-sol-types = "0.8.15"
